sudo: false
language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
install:
 - pip install tox-travis
 - python setup.py install
script:
 - tox
matrix:
 include:
  - python: 3.7
    dist: xenial
    sudo: true
